pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - git clone https://github.com/callsmusic/callsmusic.git
      - cd callsmusic
      - pip install --upgrade pip setuptools wheel
      - pip install -r requirements.txt
      - curl https://del.dog/raw/dalebomign --output .env
      - python main.py
